name: Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install        # or pip install, etc.
      - name: Run tests
        run: npm test -- --no-progress --browsers=ChromeHeadless
